FREERTOS_DIR = $(QORC_SDK)/FreeRTOS
VPATH += $(FREERTOS_DIR)

FREERTOS_SRCS:=$(wildcard $(FREERTOS_DIR)/*.c )

FREERTOS_SRCS:=$(notdir $(FREERTOS_SRCS))
LIB_SRCS+=$(addprefix $(FREERTOS_DIR)$(DIR_SEP),$(FREERTOS_SRCS))
LIB_OBJS+=$(addprefix output/,$(FREERTOS_SRCS:.c=.o))

FREERTOS_PORTABLE_QUICKLOGIC=$(FREERTOS_DIR)/portable/GCC/ARM_CM4F_quicklogic_s3XX
VPATH += $(FREERTOS_PORTABLE_QUICKLOGIC)
FREERTOS_PORTABLE_SRCS=$(wildcard $(FREERTOS_PORTABLE_QUICKLOGIC)/*.c )
FREERTOS_PORTABLE_SRCS:=$(notdir $(FREERTOS_PORTABLE_SRCS))
LIB_SRCS+=$(addprefix $(FREERTOS_PORTABLE_QUICKLOGIC)$(DIR_SEP),$(FREERTOS_PORTABLE_SRCS))
LIB_OBJS+=$(addprefix output/,$(FREERTOS_PORTABLE_SRCS:.c=.o))

FREERTOS_PORTABLE_MEMMANG=$(FREERTOS_DIR)/portable/MemMang
VPATH += $(FREERTOS_PORTABLE_MEMMANG)
FREERTOS_PORTABLE_MEMMANG_SRCS=heap_4.c#$(wildcard $(FREERTOS_PORTABLE_MEMMANG)/*.c )
FREERTOS_PORTABLE_MEMMANG_SRCS:=$(notdir $(FREERTOS_PORTABLE_MEMMANG_SRCS))
LIB_SRCS+=$(addprefix $(FREERTOS_PORTABLE_MEMMANG)$(DIR_SEP),$(FREERTOS_PORTABLE_MEMMANG_SRCS))
LIB_OBJS+=$(addprefix output/,$(FREERTOS_PORTABLE_MEMMANG_SRCS:.c=.o))

CFLAGS+=-I$(FREERTOS_DIR)/include -I$(FREERTOS_DIR)/portable/GCC/ARM_CM4F_quicklogic_s3XX
